# Generated by Django 5.2.5 on 2025-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='place',
            field=models.CharField(choices=[('HD', 'Head/Cabeçalho')], help_text='Escolha onde o script deve ser inserido.', max_length=2, verbose_name='Local'),
        ),
    ]
